# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('log_level', models.CharField(max_length=255)),
                ('log_message', models.CharField(max_length=255)),
                ('log_sender', models.CharField(max_length=255)),
                ('log_name', models.CharField(max_length=255)),
            ],
        ),
    ]
